from __future__ import annotations

import json
from pathlib import Path

from io_paths import (
    FULL_AREA_GEOJSON_DIR,
    FULL_AREA_LOG_DIR,
    FULL_AREA_RASTER_DIR,
    FULL_AREA_TABLE_DIR,
    GEOJSON_DIR,
    LOG_DIR,
    OUTPUTS_DIR,
    PIC_ALL_DIR,
    PIC_ALL_KEEP_MANIFEST,
    PROJECT_DIR,
    RASTER_ROOT,
    RESULTS_DIR,
    SAME_PIXEL_TABLE_DIR,
    SUMMARY_DIR,
    TABLE_DIR,
    TABLE_ROOT,
    TIF_DIR,
)


def rel(path: Path) -> str:
    return str(path.relative_to(PROJECT_DIR))


def current_images() -> list[str]:
    return sorted(path.name for path in PIC_ALL_DIR.glob("*.png") if path.is_file())


def snapshot() -> None:
    PIC_ALL_KEEP_MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    images = current_images()
    PIC_ALL_KEEP_MANIFEST.write_text(json.dumps({"images": images}, ensure_ascii=False, indent=2), encoding="utf-8")
    write_results_markdown()
    print(f"snapshot_images={len(images)}")


def manifest_images() -> list[str]:
    if not PIC_ALL_KEEP_MANIFEST.exists():
        return current_images()
    data = json.loads(PIC_ALL_KEEP_MANIFEST.read_text(encoding="utf-8"))
    return sorted(data.get("images", []))


def sync() -> None:
    PIC_ALL_DIR.mkdir(parents=True, exist_ok=True)
    write_results_markdown()
    print(f"pic_all_images={len(current_images())}")


def png_outside_pic_all() -> list[Path]:
    return sorted(
        path
        for path in RESULTS_DIR.rglob("*.png")
        if path.is_file() and PIC_ALL_DIR not in path.parents
    )


def count_files(root: Path, *patterns: str) -> int:
    if not root.exists():
        return 0
    return sum(1 for pattern in patterns for path in root.rglob(pattern) if path.is_file())


def maybe_line(path: Path, description: str) -> str:
    return f"- `{rel(path)}/`: {description}."


def write_results_markdown() -> None:
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)
    PIC_ALL_DIR.mkdir(parents=True, exist_ok=True)

    images = current_images()
    outside_png = png_outside_pic_all()

    (PIC_ALL_DIR / "README.md").write_text(
        "# pic_all\n\n"
        "All generated PNG figures are written here directly as a flat image collection.\n\n"
        "Figures with a geographic SAR backdrop use the current GAMMA/DSM terrain-geocoded RSLC raster. "
        "Their display stretch matches `图_02_初始投影掩膜.png`: square-root intensity to amplitude, "
        "then valid-pixel 2%-98% linear clipping. This changes display only, not raster values or coordinates.\n\n"
        f"- PNG count: `{len(images)}`\n"
        f"- PNG files outside this directory under `results/`: `{len(outside_png)}`\n\n"
        "## Files\n\n"
        + "\n".join(f"- `{name}`" for name in images)
        + ("\n" if images else ""),
        encoding="utf-8",
    )

    lines = [
        "# Results",
        "",
        "This file is generated by `code/pic_all.py`; run `python3 code/pic_all.py sync` after workflows to refresh counts.",
        "",
        "## Current Processing Basis",
        "",
        "- Geographic SAR backgrounds are terrain-geocoded with the cropped DSM using GAMMA `dem_import`, `multi_look`, `gc_map2`, `geocode_back`, and `data2geotiff`.",
        "- GDAL only reprojects the GAMMA output to EPSG:4326; no zero-height GCP/TPS or building-control-point polynomial warp is used.",
        "- Figure grayscale is display-only: square-root intensity to amplitude, valid-pixel 2%-98% clipping, then linear black-white mapping.",
        "- The current full-area summary is read from `results/outputs/summaries/20200708_full_area_summary.json`.",
        "",
        "## Directory Layout",
        "",
        "- `results/picall/主流程/`: flat PNG image collection.",
        "- `results/outputs/`: all non-image outputs.",
        "",
        "## Current Counts",
        "",
        f"- PNG figures in `results/picall/主流程/`: `{len(images)}`",
        f"- PNG files outside `results/picall/主流程/`: `{len(outside_png)}`",
        f"- CSV tables: `{count_files(TABLE_ROOT, '*.csv')}`",
        f"- GeoJSON files: `{count_files(OUTPUTS_DIR / 'geodata', '*.geojson')}`",
        f"- raster files: `{count_files(RASTER_ROOT, '*.tif', '*.vrt')}`",
        f"- summary JSON files: `{count_files(SUMMARY_DIR, '*.json')}`",
        f"- log files: `{count_files(OUTPUTS_DIR / 'logs', '*.log', '*.txt')}`",
        "",
        "## Output Folders",
        "",
        maybe_line(TABLE_DIR, "main workflow CSV tables"),
        maybe_line(FULL_AREA_TABLE_DIR, "full-area CSV tables"),
        maybe_line(SAME_PIXEL_TABLE_DIR, "same-PS-pixel CSV tables"),
        maybe_line(GEOJSON_DIR, "main workflow GeoJSON outputs"),
        maybe_line(FULL_AREA_GEOJSON_DIR, "full-area GeoJSON outputs"),
        maybe_line(TIF_DIR, "main workflow GeoTIFF rasters"),
        maybe_line(FULL_AREA_RASTER_DIR, "full-area compatibility/reference rasters"),
        maybe_line(SUMMARY_DIR, "JSON summaries and metadata"),
        maybe_line(LOG_DIR, "main workflow logs"),
        maybe_line(FULL_AREA_LOG_DIR, "full-area workflow logs"),
        maybe_line(OUTPUTS_DIR / "psinsar_same_pixel_ppt_package", "PPT support package"),
        "",
    ]
    if outside_png:
        lines.extend(["## PNG Outside pic_all", ""])
        lines.extend(f"- `{rel(path)}`" for path in outside_png)
        lines.append("")
    (RESULTS_DIR / "README.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=["snapshot", "sync"])
    args = parser.parse_args()
    if args.command == "snapshot":
        snapshot()
    else:
        sync()


if __name__ == "__main__":
    main()
